<template>
  <v-layout row justify-center >
    <div class="text-center ma-5" style="height: auto">
      <v-expansion-panels
        v-model="panel"
        multiple
        style="font-size: 25px !important"
      >
        <v-expansion-panel v-for="(question, i) in items" class="text-center">
          <v-expansion-panel-header>
            <span
              style="
                font-size: 22px !important;
                font-family: Oxanium !important;
              "
              ><strong>{{ question.q }}</strong></span
            >
          </v-expansion-panel-header>
          <v-expansion-panel-content style="text-align: start">
            <span
              style="
                font-size: 16px !important;
                font-family: Oxanium !important;
              "
              >{{ question.a }}</span
            >
          </v-expansion-panel-content>
        </v-expansion-panel>
      </v-expansion-panels>
    </div>
  </v-layout>
</template>

<script>
export default {
  data() {
    return {
      panel: [],
      items: [
        {
          q: 'What is SolMesh Project?',
          a: 'SolMeshes is a trilogy of generative art NFT collection project on Solana Universe. The Project is inspired by the beauty of geometrical shapes and the universe. The trilogy consists of SolShapes, SolMeshClassics, and SolMeshConstellations.',
        },
        {
          q: 'What is the collection size?',
          a: 'In total 1,000 SolShapes, 4,000 SolMeshClassics, and 10,000 SolMeshConstellations are generated by using 8 shape types, 2 mesh styles, 42 color combinations, 3 mesh densities, 2 dot styles, and 16 / 26 void layouts (for SolMeshClassics / SolMeshConstellations respectively).  ',
        },
        {
          q: 'When Launch?',
          a: 'SolMeshes Project will be launching on 27th November.',
        },
        {
          q: 'Will there be any giveaways?',
          a: 'Yes! 30 SolShapes will be distributed through giveaways. Follow our announcement channels (twitter, discord) for instructions.',
        },
        {
          q: 'Where do you store images?',
          a: 'Images are stored permanently on the Arweave database. They can never be deleted.',
        },
        {
          q: 'What are the prices?',
          a: '0.25 SOL for SolShapes, 0.75 SOL for SolMeshClassics, and 1.50 SOL for SolMeshConstellations.',
        },
        {
          q: 'Where can I mint?',
          a: 'The Minting page will be announced before the main sale.',
        },
        {
          q: 'Which secondary marketplaces I can use?',
          a: 'Available secondary markets will be announced soon.',
        },
        {
         q: 'What is the royalty percentage?',
         a: 'Royalties are set as 5%.',
        },
        {
          q: "What's Next?",
          a: 'New projects/collections. Stay tuned and be prepared for the beauty of shapes...',
        },
      ],
    }
  },
  components: {},
  methods: {},
  mounted() {},
}
</script>

<style></style>
